# Generated by Django 2.1.3 on 2018-12-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField()),
            ],
        ),
    ]
