# Generated by Django 2.1.3 on 2018-12-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='shortdesc',
            field=models.CharField(default='shortdesc', max_length=2048),
            preserve_default=False,
        ),
    ]
