# Generated by Django 2.1.5 on 2019-03-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpage_shortdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='body',
        ),
    ]
